### ISSUE TITLE
elasticsearch5 happen java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger

### ISSUE THREAD

**Issue by babymm** [harbby/presto-connectors#10]
2019-01-18T13:23:58.077+0800	INFO	main	Bootstrap	PROPERTY                       DEFAULT  RUNTIME              DESCRIPTION
2019-01-18T13:23:58.077+0800	INFO	main	Bootstrap	elasticsearch.cluster.name     null     elasticsearch        Elasticsearch cluster name string
2019-01-18T13:23:58.077+0800	INFO	main	Bootstrap	elasticsearch.transport.hosts  null     172.31.134.225:9300  IP:PORT where Elasticsearch Transport hosts connect
2019-01-18T13:23:58.467+0800	ERROR	main	com.facebook.presto.server.PrestoServer	org/apache/logging/log4j/Logger
java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:101)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.<init>(AbstractXContentParser.java:57)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.<init>(JsonXContentParser.java:44)
	at org.elasticsearch.common.xcontent.json.JsonXContent.createParser(JsonXContent.java:103)
	at org.elasticsearch.common.settings.Setting.parseableStringToList(Setting.java:832)
	at org.elasticsearch.common.settings.Setting.lambda$listSetting$27(Setting.java:786)
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:791)
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:786)
	at org.elasticsearch.common.network.NetworkService.<clinit>(NetworkService.java:50)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:98)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:111)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:101)
	at com.facebook.presto.elasticsearch5.Elasticsearch5Module$ConnectionProvider.get(Elasticsearch5Module.java:60)
	at com.facebook.presto.elasticsearch5.Elasticsearch5Module$ConnectionProvider.get(Elasticsearch5Module.java:39)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
	at com.facebook.presto.elasticsearch.ElasticsearchConnectorFactory.create(ElasticsearchConnectorFactory.java:68)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:320)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:121)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:68)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more

2019-01-18T13:23:58.469+0800	INFO	Thread-88	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...

**Comment by babymm** [comment]
add log4j-1.2-api-2.11.1.jar  log4j-api-2.11.1.jar      log4j-core-2.11.1.jar  can find resolv problem ,but occur 
2019-01-18T14:37:23.084+0800	ERROR	main	com.facebook.presto.server.PrestoServer	com/facebook/presto/spi/connector/ConnectorRecordSinkProvider
java.lang.NoClassDefFoundError: com/facebook/presto/spi/connector/ConnectorRecordSinkProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:80)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.facebook.presto.plugin.jdbc.JdbcModule.configure(JdbcModule.java:40)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at io.airlift.configuration.ConfigurationFactory.registerConfigurationClasses(ConfigurationFactory.java:165)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:200)
	at com.facebook.presto.plugin.jdbc.JdbcConnectorFactory.create(JdbcConnectorFactory.java:71)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:320)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:121)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:68)
Caused by: java.lang.ClassNotFoundException: com.facebook.presto.spi.connector.ConnectorRecordSinkProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:76)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more。

**Comment by harbby** [comment]
HI, you need to provide and check your presto version.
