### ISSUE TITLE
安装插件失败，public io.airlift.slice.Slice com.facebook.presto.elasticsearch6.functions.MatchQueryFunction.matchQuery(io.airlift.slice.Slice)] is an instance method. It must be in a class annotated with @ScalarFunction, and the class is required to have a public constructor.

### ISSUE THREAD

**Issue by BobEnya** [harbby/presto-connectors#5]
2018-11-08T11:42:12.819+0800    ERROR   main    com.facebook.presto.server.PrestoServer Method [public io.airlift.slice.Slice com.facebook.presto.elasticsearch6.functions.MatchQueryFunction.matchQuery(io.airlift.slice.Slice)] is an instance method. It must be in a class annotated with @ScalarFunction, and the class is required to have a public constructor.
java.lang.IllegalArgumentException: Method [public io.airlift.slice.Slice com.facebook.presto.elasticsearch6.functions.MatchQueryFunction.matchQuery(io.airlift.slice.Slice)] is an instance method. It must be in a class annotated with @ScalarFunction, and the class is required to have a public constructor.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
        at com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Parser.getConstructor(ParametricScalarImplementation.java:646)
        at com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Parser.<init>(ParametricScalarImplementation.java:513)
        at com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Parser.parseImplementation(ParametricScalarImplementation.java:710)
        at com.facebook.presto.operator.scalar.annotations.ScalarFromAnnotationsParser.parseParametricScalar(ScalarFromAnnotationsParser.java:106)
        at com.facebook.presto.operator.scalar.annotations.ScalarFromAnnotationsParser.parseFunctionDefinitions(ScalarFromAnnotationsParser.java:60)
        at com.facebook.presto.metadata.FunctionExtractor.extractFunctions(FunctionExtractor.java:57)
        at com.facebook.presto.server.PluginManager.installPlugin(PluginManager.java:200)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:172)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:156)
        at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:137)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:117)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

**Comment by icelemonna** [comment]
遇到过这个问题，参考了其他plugin里面函数的声明方式，把matchQuery和matchPhrase声明为public static，再给类加一个private的构造函数，内容为空即可。

![image](https://user-images.githubusercontent.com/27984637/48191530-4b184180-e380-11e8-81a7-f0aadbe90b2e.png)

**Comment by ciscoring** [comment]
I had same issues. I changed the codes below. convert all methods of MatchQueryFunction to static.
`/**
 * 输入bitmap 输出该bitmap的值
 */
public class MatchQueryFunction
{
    public static final String MATCH_COLUMN_SEP = "__%s@#$%^&*()_+~";

    @ScalarFunction("match_query")
    @Description("es match_query")
    @SqlType(StandardTypes.VARCHAR)
    @SqlNullable
    public static Slice matchQuery(
            @SqlType(StandardTypes.VARCHAR) Slice filter)
    {
        if (filter == null) {
            return null;
        }
        String filterStr = filter.toStringUtf8();

        QueryBuilder builder = QueryBuilders.matchQuery(MATCH_COLUMN_SEP, filterStr);
        return Slices.utf8Slice(builder.toString());
    }

    @ScalarFunction("match_phrase")
    @Description("es match_phrase")
    @SqlType(StandardTypes.VARCHAR)
    @SqlNullable
    public static Slice matchPhrase(
            @SqlType(StandardTypes.VARCHAR) Slice filter)
    {
        if (filter == null) {
            return null;
        }
        String filterStr = filter.toStringUtf8();

        QueryBuilder builder = QueryBuilders.matchPhraseQuery(MATCH_COLUMN_SEP, filterStr);
        return Slices.utf8Slice(builder.toString());
    }
}`

**Comment by harbby** [comment]
这个应该是0.210版本 检查的更加严格所致,我会尽快进行测试和更正

ciscoring <notifications@github.com> 于2018年11月9日周五 下午3:49写道：

**Comment by harbby** [comment]
@ciscoring  Thank you for the test, I will change it as soon as possible.

**Comment by harbby** [comment]
@icelemonna  非常感谢
