### ISSUE TITLE
NullPointerException: null value in entry:

### ISSUE THREAD

**Issue by harbby** [harbby/presto-connectors#7]
Hi,

Below is the stack trace.

java.lang.NullPointerException: null value in entry: status_id_str=null
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:34)
        at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49)
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172)
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248)
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:263)
        at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:291)
        at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:274)
        at com.facebook.presto.elasticsearch6.Elasticsearch6Client$1.lambda$null$0(Elasticsearch6Client.java:352)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        at com.facebook.presto.elasticsearch6.Elasticsearch6Client$1.hasNext(Elasticsearch6Client.java:366)
        at com.facebook.presto.elasticsearch.io.ElasticsearchPageSource.getNextPage(ElasticsearchPageSource.java:132)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$318(Driver.java:278)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Thanks,
Naveen

**Comment by harbby** [comment]
Reported by `Mahadevuni Naveen Kumar`

**Comment by harbby** [comment]
Repaired by 85090f1

**Comment by nmahadevuni** [comment]
Thank you @harbby

**Comment by harbby** [comment]
@nmahadevuni  You are Welcome!

**Comment by harbby** [comment]
Hi, can I close it?

**Comment by icelemonna** [comment]
Thank you~
